name: R Script

on:
  schedule:
    - cron: "0 14 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v1
      with:
        r-version: "4.x"

    - name: Install dependencies
      run: |
        Rscript -e 'install.packages(c("tseries", "dplyr", "tidyr", "zoo", "lubridate", "alfred"))'

    - name: Execute R script
      run: Rscrip real_time_data_import.R
