name: R Script

on:
#   schedule:
#    - cron: "40 6 * * *"
#  push:
#    branches:
#      - main

permissions : 
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache R packages
      uses: actions/cache@v2
      env:
        R_LIBS_USER: ${{ github.workspace }}/R/library 
      with:
         path: ${{ env.R_LIBS_USER }}
         key: ${{ runner.os }}-R-${{ hashFiles('**/DESCRIPTION.lock') }}
         restore-keys: |
           ${{ runner.os }}-R-   
#    - name: Check the dependency cache
#      id: check-cache
#      uses: actions/cache@v2
#      with:
#        path: ${{ runner.home }}/R/Library
#        key: ${{runner.os}}-r-packages-$

#    - if: ${{ steps.check-cache.outputs.cache-hit != 'true' }}
    - name: Install R & dependencies
      run: |
        apt install R --nogpgcheck
        apt install openssl-devel
        apt install libcurl-devel
        R -q -e "install.packages(c('curl'))"
        Rscript -e 'install.packages(c("curl", "jsonlite", "devtools", "GetoptLong"))'
        Rscript -e "library(devtools)"

    - name: Execute R script
      run: Rscript market_price.R --hostname <hostname>

